version: '3.8'

services:
  # Serviço do Portfolio (Frontend + Backend)
  portfolio:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://portfolio:portfolio123@postgres:5432/portfolio_db
      - NEXTAUTH_SECRET=your-super-secret-key-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - portfolio_uploads:/app/public/uploads
    networks:
      - portfolio_network
    restart: unless-stopped

  # Serviço do PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portfolio_network
    restart: unless-stopped

  # Serviço do Redis (opcional - para cache/sessões)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - portfolio_network
    restart: unless-stopped
    command: redis-server --appendonly yes

# Volumes para persistência de dados
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  portfolio_uploads:
    driver: local

# Rede interna para comunicação entre serviços
networks:
  portfolio_network:
    driver: bridge
