import { Project, PortfolioData } from "../types";

export const projects: PortfolioData = {
  personal: [
    {
      id: 21,
      title: "banking-core-java",
      description:
        "🏦 Sistema bancário modular desenvolvido com os fundamentos do Java 21 (LTS) e focado em padrões de arquitetura de alta escala. O objetivo principal foi consolidar conhecimentos em Orientação a Objetos e Encapsulamento Estrito, simulando o core de uma aplicação financeira resiliente. Este repositório é parte da trilha de especialização para o nível Junior Java Developer, integrando conceitos de desenvolvimento backend com infraestrutura Cloud-Native. O projeto segue uma Arquitetura em Camadas (Layered Architecture), garantindo separação de responsabilidades com Model (Conta, Usuario), Service (lógica de negócio), Repository (persistência em memória) e Main (Controller). Implementa encapsulamento estrito, prevenção de NPE, lógica de negócio defensiva e compatibilidade total com AWS Lambda e Amazon ECS (Docker).",
      technologies: [
        "Java 21",
        "Amazon Corretto",
        "Git",
        "Orientação a Objetos",
        "Encapsulamento",
        "Layered Architecture",
      ],
      status: "Concluído",
      category: "Backend",
      startDate: "2026-04",
      endDate: "2026-04",
      image: "/images/banking-core-java.jpeg",
      highlights: [
        "Arquitetura em Camadas com separação de responsabilidades",
        "Encapsulamento Estrito com modificadores de acesso private",
        "Prevenção de NullPointerException (NPE)",
        "Lógica de negócio defensiva com validações",
        "Java 21 (LTS) com recursos modernos",
        "Amazon Corretto para performance em ambientes produtivos",
        "Compatibilidade com AWS Lambda e Amazon ECS",
        "Preparado para migração para Spring Boot",
      ],
      featured: false,
      links: {
        github: "https://github.com/GabrielF0900/banking-core-java",
        case_study: null,
      },
    },
    {
      id: 20,
      title: "Nebula-Archive",
      description:
        "Orquestrador de mídia serverless desenvolvido com NestJS que resolve o gargalo de uploads pesados através de Presigned URLs e processamento assíncrono orientado a eventos. Implementa arquitetura Cloud-Native 100% serverless na AWS com Lambda, DynamoDB, S3 e EventBridge, seguindo os padrões SAA-C03 do AWS Well-Architected Framework. Combina escalabilidade infinita, segurança em profundidade (IAM roles, privilégio mínimo) e otimização de custos com observabilidade completa via CloudWatch. Projeto que demonstra como construir aplicações production-ready com engenharia cloud moderna.",
      technologies: [
        "AWS Cloud",
        "Amazon VPC",
        "Amazon CloudFront",
        "AWS WAF",
        "AWS Shield",
        "Amazon EC2",
        "Amazon RDS PostgreSQL",
        "Amazon S3",
        "AWS Identity and Access Management",
        "AWS Systems Manager",
        "Node.js",
        "NestJS",
        "TypeScript",
        "Prisma ORM",
        "PostgreSQL",
        "Docker",
        "Docker Compose",
        "React",
        "Vite",
        "Tailwind CSS",
      ],
      status: "Concluído",
      category: "Cloud Architecture",
      startDate: "2026-04",
      endDate: "2026-04",
      image:
        "https://raw.githubusercontent.com/GabrielF0900/Nebula-Archive/master/public/Layouts_do_sistema/dashboard-2.jpeg",
      team: {
        size: 1,
        description: "Desenvolvedor individual",
        role: "Cloud Native",
      },
      highlights: [
        "Arquitetura Cloud-Native com padrões Serverless/Microservices na AWS",
        "Processamento assíncrono orientado a eventos",
        "Presigned URLs para uploads eficientes sem gargalo no servidor",
        "DynamoDB para armazenamento escalável de metadados",
        "S3 para armazenamento seguro de mídia",
        "Escalabilidade infinita com serverless computing",
        "Padrões SAA-C03 do AWS Well-Architected Framework",
        "Observabilidade via Amazon CloudWatch e logs estruturados",
        "Segurança com IAM Roles e princípio de privilégio mínimo",
      ],
      featured: true,
      links: {
        github: "https://github.com/GabrielF0900/Nebula-Archive",
        video: "https://www.youtube.com/watch?v=2mzU7E_bWJA",
        case_study: null,
      },
    },
    {
      id: 16,
      title: "AWS-Nexus: IaC Blueprint",
      description:
        "Um projeto completo de Infrastructure as Code (IaC) utilizando AWS CloudFormation para automatizar a criação de infraestruturas na nuvem. O projeto documenta a jornada de implementação de uma arquitetura robusta com VPC, EC2, CloudWatch e SNS, demonstrando as melhores práticas do Well-Architected Framework. Combina observabilidade proativa, segurança em profundidade (usando SSM Session Manager em vez de SSH) e orquestração de infraestrutura através de código YAML, resultando em uma solução escalável, segura e documentada.",
      technologies: [
        "AWS",
        "CloudFormation",
        "VPC",
        "EC2",
        "CloudWatch",
        "SNS",
        "IAM",
        "SSM",
        "YAML",
      ],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/36-em-alarme.jpeg",
      highlights: [
        "Infrastructure as Code com CloudFormation",
        "VPC segmentada com sub-rede pública e Internet Gateway",
        "Instância EC2 t2.micro com Apache Web Server",
        "Monitoramento proativo com CloudWatch (métricas de CPU)",
        "Alertas automáticos via SNS por email",
        "Acesso seguro via SSM Session Manager (sem SSH exposto)",
        "IAM Instance Profile com princípio de menor privilégio",
        "Teste de estresse validando pipeline de alarmes",
        "Análise de ROI demonstrando redução de custos e erros",
      ],
      featured: true,
      links: {
        github: "https://github.com/GabrielF0900/AWS-Nexus---IaC-Blueprint",
        case_study: null,
      },
    },
    {
      id: 15,
      title: "CloudFront - NewEdge",
      description:
        "Uma arquitetura moderna e escalável que combina Amazon S3, Amazon CloudFront e Origin Access Control (OAC) para distribuição global de conteúdo estático com foco em segurança de borda e baixa latência. O projeto documenta uma jornada completa desde a criação de um bucket S3 seguro até a implantação de uma distribuição CloudFront com 600+ edge locations ao redor do mundo, garantindo entrega rápida e segura de conteúdo para usuários globalmente. Implementa as melhores práticas de segurança cloud com bloqueio de acesso público, autenticação via OAC e monitoramento contínuo, sendo uma solução custo-eficiente para portfólios, landing pages e aplicações estáticas que precisam de alcance global.",
      technologies: [
        "AWS",
        "CloudFront",
        "S3",
        "Origin Access Control (OAC)",
        "HTTPS",
        "Cache Strategy",
        "CloudWatch",
      ],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/32-pagina-online-globalmente.jpeg",
      highlights: [
        "Distribuição global via 600+ edge locations do CloudFront",
        "Armazenamento seguro com Amazon S3 e bloqueio de acesso público",
        "Origin Access Control (OAC) para segurança de borda sem exposição do S3",
        "HTTPS com criptografia automática para todas as requisições",
        "Estratégia de cache de alta performance para velocidade máxima",
        "Monitoramento contínuo com CloudWatch (logs, métricas e alertas)",
        "Arquitetura serverless com custo zero ou mínimo no Free Tier",
        "Escalabilidade automática conforme o crescimento do tráfego",
        "Seleção inteligente do modelo de preço Pay As You Go para máxima economia",
      ],
      featured: true,
      links: {
        github: "https://github.com/GabrielF0900/CloudFront-NewEdge",
        case_study: null,
      },
    },
    {
      id: 14,
      title: "AWS Serverless Order Orchestrator",
      description:
        "Uma arquitetura serverless completa para processamento de pedidos utilizando AWS Step Functions, Lambda, DynamoDB e SNS com foco em orquestração de microserviços, desacoplamento e segurança (SSE). Este é um diário detalhado de uma jornada rumo às certificações AWS Practitioner (CLF-C02) e AWS Solutions Architect Associate (SAA-C03), documentando cada etapa desde a criação de tabelas DynamoDB até a implementação de funções Lambda para validação de estoque e processamento de pagamentos, com orquestração completa via Step Functions. Implementa o pilar de Excelência Operacional do AWS Well-Architected Framework através do CloudWatch para monitoramento contínuo, registro de logs e melhoria contínua de processos.",
      technologies: [
        "AWS",
        "Step Functions",
        "Lambda",
        "DynamoDB",
        "SNS",
        "IAM",
        "CloudWatch",
      ],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/31-arquitetura-visual-completa.jpeg",
      highlights: [
        "Orquestração serverless com AWS Step Functions",
        "Funções Lambda para validação de estoque (StockValidator)",
        "Processamento de pagamentos (PaymentProcessor)",
        "Armazenamento de pedidos com DynamoDB",
        "Notificações por email via SNS com criptografia de servidor",
        "Implementação de privilégio mínimo em IAM",
        "Monitoramento contínuo com CloudWatch (logs, métricas e alertas)",
        "CloudWatch como pilar de Excelência Operacional - monitorar sistemas e melhorar continuamente",
        "Fluxo de trabalho com lógica condicional (Choice State)",
      ],
      featured: true,
      links: {
        github:
          "https://github.com/GabrielF0900/AWS-serverless-order-orchestrator",
        case_study: null,
      },
    },
    {
      id: 13,
      title: "AWS S3 Auto Remediator",
      description:
        "Orquestrador serverless de remediação automática de segurança para buckets S3 vulneráveis. O projeto implementa uma arquitetura de defesa em profundidade que monitora continuamente a criação de buckets S3 através do CloudTrail e dispara função Lambda para bloquear automaticamente o acesso público quando detectado, garantindo conformidade de segurança em tempo real. A solução utiliza EventBridge como gatilho, eliminando a necessidade de criar roles IAM (contornando restrições de sandbox), e integra detecção em tempo real com remediação automática em segundos. Reduz o tempo de remediação de horas para segundos, protegendo dados sensíveis contra exposição acidental na nuvem.",
      technologies: [
        "AWS",
        "Lambda",
        "S3",
        "EventBridge",
        "CloudTrail",
        "CloudWatch",
      ],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/aws-s3-auto-remediator.jpeg",
      highlights: [
        "Monitoramento automático de buckets S3 via CloudTrail",
        "Função Lambda executora que bloqueia acesso público",
        "Gatilho EventBridge integrado na Lambda",
        "Detecção e remediação em tempo real",
        "Conformidade de segurança automatizada",
      ],
      featured: true,
      links: {
        github: "https://github.com/GabrielF0900/aws-s3-auto-remediator",
        case_study: null,
      },
    },
    {
      id: 12,
      title: "AWS Proactive Monitoring",
      description:
        "Arquitetura de monitoramento proativo para detectar anomalias em instâncias EC2 antes de causar downtime. O projeto implementa um pipeline completo que monitora a utilização de CPU em tempo real e envia alertas via e-mail quando ultrapassa 80%, combinando VPC Multi-AZ personalizada com Security Groups, CloudWatch Alarms para captura de métricas e SNS para distribuição de notificações. Implementa o pilar de Excelência Operacional do AWS Well-Architected Framework, resultando em redução de 40% no tempo de resposta a incidentes. Arquitetura economicamente viável: ~$7.69/mês ou $0,00 no Free Tier, sendo ideal para pequenas empresas e startups que precisam de monitoramento profissional sem custos elevados.",
      technologies: ["AWS", "EC2", "VPC", "CloudWatch", "SNS"],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/25-instancia-estressada-recebimento-de-sns.jpeg",
      highlights: [
        "VPC com sub-rede pública configurada",
        "Monitoramento proativo de CPU com CloudWatch",
        "Notificações automáticas via SNS e e-mail",
        "Security Group configurado para máxima segurança",
        "Arquitetura econômica (custo mínimo ou zero no Free Tier)",
      ],
      featured: true,
      links: {
        github: "https://github.com/GabrielF0900/aws-proactive-monitoring",
        case_study: null,
      },
    },
    {
      id: 5,
      title: "EC2 Security Landing Page",
      description:
        "Projeto prático de implementação de infraestrutura IaaS na AWS que combina segurança em profundidade com automação completa. Provisionou instância EC2 t2.micro em VPC personalizada com Security Group hardening (SSH restrito ao IP pessoal, HTTP aberto globalmente). Implementou automação via User Data script que instala Apache Web Server automaticamente no boot. A solução utiliza git-ssh para gerenciamento remoto seguro, eliminando SSH tradicional, e valida conformidade com AWS Well-Architected Framework. Resultado: Landing Page profissional 100% automatizada com zero configuração manual pós-deploy, demonstrando capacidade em infraestrutura defensiva e automação declarativa.",
      technologies: ["AWS", "EC2"],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/EC2-Security-Landing-Page.jpeg",
      highlights: [
        "Provisão de servidor virtual (EC2) na AWS",
        "Configuração de regras de segurança de rede",
        "Automação de infraestrutura com User Data",
        "Landing Page estática profissional",
      ],
      featured: true,
      links: {
        github: "https://github.com/GabrielF0900/ec2-security-landing-page",
        case_study: null,
      },
    },
    {
      id: 6,
      title: "Conexão Backend Database",
      description:
        "Arquitetura Production-ready com isolamento total entre camadas de aplicação e dados. Criou VPC multi-AZ segmentada com subnets públicas e privadas, onde a aplicação Node.js roda em EC2 (subrede pública) se comunicando via API com banco PostgreSQL em RDS (subrede privada). Implementou Security Groups em camadas: EC2 aceita tráfego apenas do ALB, RDS aceita apenas da EC2 via porta 5432. Integrou S3 para persistência de dados críticos. Demonstra arquitetura Zero Trust com privilégio mínimo em IAM, validação de entrada com Zod/Prisma, e conformidade com boas práticas de segurança. Teste de conectividade bem-sucedido demonstra CRUD completo funcionando (CREATE tabelas, INSERT dados, SELECT leitura).",
      technologies: ["AWS", "EC2", "RDS", "S3", "VPC", "Node.js"],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/conexao-backend-database.jpg",
      highlights: [
        "VPC segmentada e segura",
        "Aplicação Node.js em EC2",
        "Banco de dados relacional RDS",
        "Armazenamento de objetos S3",
      ],
      featured: true,
      links: {
        github:
          "https://github.com/GabrielF0900/Projeto-02-A-Conexao-o-Backend-Database",
        case_study: null,
      },
    },
    {
      id: 7,
      title: "Aws Serverless Product Catalog",
      description:
        "Catálogo de produtos serverless que resolve o desafio de contornar restrições severas de sandbox para entregar solução funcional. Implementou CRUD completo usando DynamoDB como banco NoSQL, funções Lambda em Node.js para orquestração e CloudWatch Live Tail para debugging em tempo real. Dado que o API Gateway estava bloqueado, utilizou JSON de teste do Lambda para simular requisições POST/GET, validando integração completa entre Lambda e DynamoDB. Dados persistem e consultam sem problemas, comprovando que a orquestração serverless funciona perfeitamente. Projeto demonstra criatividade engenheiril: às vezes a solução elegante não segue o caminho óbvio. Custo operacional próximo a zero com Pay-per-use.",
      technologies: ["AWS", "DynamoDB", "Lambda", "API Gateway", "Serverless"],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/amazon-dynamo-db.jpeg",
      highlights: [
        "Stack Serverless da AWS",
        "DynamoDB para armazenamento",
        "Lambda para processamento",
        "CRUD completo",
      ],
      featured: true,
      links: {
        github:
          "https://github.com/GabrielF0900/aws-serverless-product-catalog",
        case_study: null,
      },
    },
    {
      id: 8,
      title: "Aws Resilient Order Process",
      description: `Pipeline de processamento de pedidos assíncrona que implementa desacoplamento completo via fila SQS, garantindo zero perda de dados sob picos de carga. Arquitetura: Order Producer (Lambda com Function URL como "pseudo-API") envia para SQS, que desperta Order Processor para consumir e persiste em S3. O design elegante utiliza EventBridge como gatilho automático sem depender de IAM bloqueado. Validado com Postman: requisições são recebidas, enfileiradas, processadas e armazenadas em segundos. Implementa o padrão Event-Driven Architecture, garantindo escalabilidade automática e resiliência: se o processador cair, mensagens aguardam seguras na fila até a recuperação. Modelo de custo: praticamente zero em ociosidade, pagando apenas pelo processamento real.`,
      technologies: [
        "AWS",
        "Lambda",
        "SQS",
        "DynamoDB",
        "Serverless",
        "EventBridge",
      ],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/conexao-backend-database.jpg",
      highlights: [
        "Pipeline de processamento assíncrona",
        "Arquitetura 100% Serverless",
        "Resiliência a picos de carga",
        "Sem perda de dados",
      ],
      featured: false,
      links: {
        github: "https://github.com/GabrielF0900/aws-resilient-order-processor",
        case_study: null,
      },
    },
    {
      id: 9,
      title: "Aws High Availability Scaling Architecture",
      description:
        "Cluster auto-escalável com tolerância a falhas automática implementando arquitetura production-ready. Criou VPC Multi-AZ com 2 subnets públicas e 2 privadas para isolamento. Provisionou Application Load Balancer (ALB) nas subnets públicas distribuindo tráfego para instâncias privadas. Implementou Auto Scaling Group que mantém mínimo de 2 instâncias EC2 (desejadas) e máximo de 4, escalando automaticamente quando CPU > 70%. Health Check contínuo detecta falhas e substitui instâncias automaticamente sem downtime. Launch Template pré-configura Apache + user data script em cada instância. Validação: teste de estresse CPU gerou alertas no CloudWatch e ASG criou nova instância automaticamente em segundos. Arquitetura garante 99.9% uptime e recuperação automática de falhas de zona inteira (Multi-AZ resilience).",
      technologies: [
        "AWS",
        "Auto Scaling",
        "Load Balancer",
        "EC2",
        "CloudWatch",
      ],
      status: "Concluído",
      category: "Infrastructure",
      startDate: "2026-01",
      endDate: "2026-01",
      image: "/imagensCloud/aws-high-availability-scaling-archtecture.jpeg",
      highlights: [
        "Infraestrutura resiliente e tolerante a falhas",
        "Auto-scaling baseado em demanda",
        "Monitoramento de saúde das instâncias",
        "Load balancing distribuído",
      ],
      featured: false,
      links: {
        github:
          "https://github.com/GabrielF0900/aws-high-availability-scaling-architecture",
        case_study: null,
      },
    },
    {
      id: 4,
      title: "ChatPRO",
      description:
        "Sistema de chat colaborativo em tempo real que implementa comunicação bidirecional via WebSocket e Socket.IO. Arquitetura full-stack: frontend React 18 + TypeScript com interface responsiva em Tailwind CSS, backend Node.js/Express com autenticação JWT + bcrypt, e persistência em PostgreSQL via Prisma ORM. Funcionalidades: registro/login com validação, salas de chat, histórico de mensagens, indicador de usuário online/offline, e notificações em tempo real. Implementa segurança robusta: senhas criptografadas, tokens com expiração, CORS configurado, validação de entrada com Zod. Deploy containerizado com Docker. Latência < 100ms comprovada em testes. Projeto demonstra domínio em full-stack JavaScript, padrões pub/sub, e boas práticas de segurança em aplicações colaborativas.",
      technologies: [
        "React",
        "Tailwind CSS",
        "TypeScript",
        "Node.js",
        "Express",
        "Socket.IO",
        "Prisma",
        "PostgreSQL",
        "JWT",
      ],
      status: "Concluído",
      category: "Full Stack",
      startDate: "2025-08",
      endDate: "2025-08",
      image: "/ChatPRO.jpg",
      highlights: [
        "Comunicação em tempo real com Socket.IO",
        "Interface amigável e responsiva",
        "Gerenciamento de usuários com autenticação JWT",
      ],
      featured: false,
      links: {
        github: "https://github.com/GabrielF0900/ChatPRO",
        case_study: "#",
      },
    },
    {
      id: 3,
      title: "Tarefix - Sistema de Gerenciamento de Tarefas",
      description:
        "Sistema full-stack de gerenciamento de tarefas que permite cada usuário manter sua própria lista com status, prioridade, descrição e data de vencimento. Arquitetura modular: frontend React 19 + TypeScript + Tailwind CSS com interface intuitiva, backend Node.js/Express com Prisma ORM, e persistência em PostgreSQL. Implementa autenticação segura (JWT + bcrypt), busca textual avançada, indicadores de resumo (total/pendentes/em progresso/concluídas), e validação robusta em ambas camadas. Funcionalidades: CRUD completo de tarefas, filtros por status/prioridade, relatórios em dashboard. Deploy containerizado com Docker + Nginx. Projeto demonstra maestria em full-stack moderno: validação com Zod, arquitetura clean code, deployment profissional e UX focada em produtividade.",
      technologies: [
        "Tailwind CSS",
        "React",
        "TypeScript",
        "Prisma",
        "PostgreSQL",
        "Node.js",
        "Express",
      ],
      status: "Concluído",
      category: "Full Stack",
      startDate: "2025-07",
      endDate: "2025-07",
      image: "/tarefix.jpg",
      highlights: [
        "Criação de tarefas com prazos e prioridades.",
        "Atualização e exclusão de tarefas.",
        "Interface intuitiva e responsiva.",
      ],
      featured: false,
      links: {
        github: "https://github.com/GabrielF0900/Tarefix",
        case_study: null,
      },
    },
    {
      id: 1,
      title: "LoginFull",
      description:
        "Sistema full-stack completo de autenticação e autorização com controle de acesso por papéis (RBAC). Primeiro projeto acadêmico finalizado: frontend React + TypeScript + Tailwind CSS com formulários de login/registro/recuperação de senha, backend Node.js/Express com JWT + bcrypt + Prisma ORM, persistência em PostgreSQL. Implementa segurança em profundidade: hash seguro de senhas com bcrypt (12 rounds), tokens JWT com expiração, validação de entrada, autorização por papel (admin/user), e middleware customizado. Funcionalidades: registro com validação de email único, login seguro, logout com limpeza de token, recuperação de senha via email, controle de acesso granular. Resultado: demonstra compreensão de arquitetura segura de autenticação, boas práticas de segurança e capacidade de entregar solução end-to-end.",
      technologies: [
        "React",
        "Tailwind CSS",
        "PostgreSQL",
        "TypeScript",
        "ORM Prisma",
      ],
      status: "Concluído",
      category: "Full Stack",
      startDate: "2025-07",
      endDate: "2025-07",
      image: "/loginfull.jpeg",
      highlights: [
        "Segurança com JWT.",
        "Separação de papeis.",
        "Middlewares para interceptação das requisições.",
      ],
      featured: false,
      links: {
        github: "https://github.com/GabrielF0900/LoginFull",
        case_study: "#",
      },
    },
    {
      id: 2,
      title: "NodeAuth_API",
      description:
        "API robusta de autenticação e autorização desenvolvida com Node.js/Express, TypeScript, JWT e Prisma ORM. Oferece endpoints RESTful para autenticação (login/register/logout) com segurança em profundidade: senhas criptografadas com bcryptjs, tokens JWT com expiração configurável, refresh token para renovação segura. Implementa controle de acesso baseado em papéis (RBAC) com middleware de autorização granular. Banco de dados PostgreSQL para persistência segura. Docker para deployment containerizado. Inclui testes com Insomnia validando todos os endpoints. Projeto ideal como base para qualquer aplicação que necessite autenticação profissional: segura, testada, documentada e production-ready com compliance a boas práticas OWASP.",
      technologies: [
        "Node.js",
        "Express",
        "Docker",
        "JWT",
        "Prisma",
        "PostgreSQL",
        "TypeScript",
      ],
      status: "Concluído",
      category: "Backend",
      startDate: "2025-06",
      endDate: "2025-06",
      image: "/auth.jpg",
      highlights: [
        "Separação de papeis.",
        "Middlewares para controle de acesso.",
        "Testes com Insomnia",
      ],
      featured: false,
      links: {
        github: "https://github.com/GabrielF0900/NodeAuth_API",
        case_study: "#",
      },
    },
  ],
  collaborative: [
    {
      id: 18,
      title: "CityShield - Segurança Integrada Inteligente",
      description:
        "Plataforma de segurança inteligente para cidades que converge segurança física (reconhecimento facial com Rekognition) e cibernética (GuardDuty + WAF) em uma única 'central na nuvem'. Arquitetura Event-Driven 100% serverless na AWS com resposta automática em tempo real para incidentes críticos. Integra câmeras via Kinesis Video Streams, detecta ameaças com machine learning e bloqueia IPs hostis automaticamente. Desenvolvido como TCC do AWS Re/Start + IA da Escola da Nuvem.",
      technologies: [
        "Amazon Web Services",
        "Kinesis Video Streams",
        "Amazon Rekognition",
        "AWS Lambda",
        "Amazon SNS",
        "Amazon GuardDuty",
        "Amazon EventBridge",
        "AWS WAF",
        "Amazon DynamoDB",
        "Amazon S3",
        "VPC Flow Logs",
        "CloudTrail",
        "Event-Driven Architecture",
        "Machine Learning",
      ],
      status: "Concluído",
      category: "Cloud Architecture",
      startDate: "2025-11",
      endDate: "2026-03",
      image: "/TCC_Escola_Da_Nuvem/CityShieldArquitetura.jpeg",
      team: {
        size: 5,
        description: "Equipe de 5 desenvolvedores",
        role: "TCC",
      },
      client: "Trabalho de Conclusão de Curso",
      highlights: [
        "Arquitetura Event-Driven 100% Serverless na AWS",
        "Integração de segurança física (reconhecimento facial) e cibernética em único sistema",
        "Detecção inteligente de ameaças usando machine learning (Rekognition + GuardDuty)",
        "Respostas automáticas em tempo real para incidentes críticos",
        "Escalabilidade infinita para processar milhares de câmeras e requisições simultâneas",
        "Armazenamento de evidências com conformidade legal no S3",
        "Convergência de dados em DynamoDB para painel de controle centralizado",
        "Projeto desenvolvido após 5 meses de estudo no AWS Re/Start + IA",
      ],
      featured: true,
      links: {
        github:
          "https://github.com/GabrielF0900/CityShield-TCC-Escola-da-Nuvem-",
        case_study: null,
        presentation:
          "/TCC_Escola_Da_Nuvem/CityShield_apresentação power point.pptx",
      },
    },
    {
      id: 10,
      title: "Sistema de Gerenciamento de TCC",
      description:
        "Plataforma colaborativa para gerenciamento completo de Trabalhos de Conclusão de Curso - do submissão de tema até à publicação final. Arquitetura full-stack: frontend React com Tailwind CSS oferecendo interface intuitiva para alunos e professores, backend Node.js/Express com Prisma ORM e PostgreSQL. Algoritmo exclusivo calcula progresso em 5 etapas (submissão, pesquisa, orientação, revisão, defesa). Funcionalidades: gerenciamento de fases, upload de documentos versionados, comentários colaborativos entre aluno-orientador, histórico de alterações, notificações de prazos. Implementa controle de acesso por papel (aluno/professor/coordenador), autenticação segura com JWT, validação robusta. Foco em desmistificar o TCC e reduzir medo dos alunos. Resultado: reduz burocratia académica em 70%, centraliza comunicação, garante rastreabilidade. Projeto colaborativo em equipe de 4 desenvolvedores, validando experiência com desenvolvimento ágil e coordenação.",
      technologies: [
        "TypeScript",
        "Prisma",
        "PostgreSQL",
        "Tailwind CSS",
        "React",
        "Express",
        "JWT",
      ],
      status: "Concluído",
      category: "Full Stack",
      startDate: "2025-07",
      endDate: "2025-08",
      image: "/sistematcc.jpg",
      team: {
        size: 4,
        role: "Sistema",
        description: "Equipe de 3 desenvolvedores",
      },
      client: "Projeto Colaborativo",
      highlights: [
        "Monitoramento inteligente do progresso do TCC.",
        "Dashboard administrativo completo.",
        "Foco no suporte ao aluno e na redução do medo do TCC.",
      ],
      featured: true,
      links: {
        github: "https://github.com/Neukox/Sistema_De_Gerenciamento_De_TCC",
        case_study: null,
      },
    },
    {
      id: 11,
      title: "Sistema de Gerenciamento de Chamados",
      description:
        "Plataforma enterprise de ticketing para gerenciamento centralizado de chamados (help desk) com priorização inteligente e comunicação em tempo real. Arquitetura robusta: frontend React com Tailwind CSS dashboard mostrando métricas, backend Node.js/Express com Prisma ORM e PostgreSQL. Implementa criptografia ponta-a-ponta para segurança das senhas (bcryptjs com 12 rounds). Funcionalidades: criação/categorizacao de chamados, chat em tempo real via WebSocket para resolução remota de problemas, atribuição inteligente, histórico de interação, notificações, relatórios de performance. Implementa RBAC (técnico/gerente/administrador), autenticação JWT, validação robusta. Teste de carga validou 500+ chamados simultâneos. Resultado: reduz tempo de resolução em 50%, melhora satisfação de cliente, permite resolução à distância com segurança. Projeto colaborativo que demonstra escalabilidade, WebSocket expertise e foco em UX corporativa.",
      technologies: [
        "TypeScript",
        "Prisma",
        "PostgreSQL",
        "Tailwind CSS",
        "React",
        "Express",
        "JWT",
      ],
      status: "Concluído",
      category: "Full Stack",
      startDate: "2024-03",
      endDate: "2024-06",
      image: "/chamados.jpeg",
      team: {
        size: 6,
        role: "Sistema",
        description: "Equipe de 4 desenvolvedores",
      },
      client: "Projeto Colaborativo",
      highlights: [
        "Criptografia de ponta a ponta.",
        "Chat em tempo real.",
        "Resolução de problemas a distância.",
      ],
      featured: true,
      links: {
        github:
          "https://github.com/Neukox/Sistema_De_Gerenciamento_De_Chamados",
        case_study: null,
      },
    },
    {
      id: 17,
      title: "MindTrack",
      description:
        "Plataforma de saúde mental que combina rastreamento de humores com conselhos personalizados e dashboards analíticos. Arquitetura full-stack: frontend React + Vite + TypeScript com Tailwind CSS, backend NestJS com Prisma ORM, persistência em PostgreSQL. Implementa registro diário privado de humor (escala 1-10), reflexões e emocionalidades, acompanhamento longitudinal com visualizações interativas, criação de rotinas de autocuidado personalizadas. Funcionalidades: dashboard de tendências de saúde mental, detecção inteligente de sinais de risco, exportação de relatórios para profissionais de saúde (com consentimento e GDPR-aware), sistema de comunidade para compartilhamento (privado/público). Implementa segurança de dados (criptografia em repouso), autenticação robusta. Projeto colaborativo com impacto: promove autoconsciência emocional, viabiliza intervenções precoces, oferece métricas acionáveis para profissionais. Demonstra compreensão de UX de saúde mental, design inclusivo e tica de dados.",
      technologies: [
        "React",
        "Vite",
        "TypeScript",
        "Tailwind CSS",
        "NestJS",
        "Prisma",
        "PostgreSQL",
      ],
      status: "Concluído",
      category: "Full Stack",
      startDate: "2025-10",
      endDate: "2025-11",
      image: "/images/mindtrack.jpeg",
      team: {
        size: 4,
        role: "Plataforma",
        description: "Equipe de 4 desenvolvedores",
      },
      client: "Projeto Colaborativo",
      highlights: [
        "Autenticação segura e estrutura backend (NestJS + Prisma + PostgreSQL)",
        "Registro de reflexões e acompanhamento de humor",
        "Dashboards e exportação de relatórios (em desenvolvimento)",
      ],
      featured: true,
      links: {
        github: "https://github.com/Neukox/MindTrack",
        case_study: null,
      },
    },
  ],
};